name: news_api_flutter_package
description: Flutter package for accessing News API. (https://newsapi.org/)
version: 1.1.0
homepage: https://github.com/sharmadhiraj/news_api_flutter_package

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: